### ISSUE TITLE
Question about few-shot evaluation

### ISSUE THREAD

**Issue by beichenzbc** [sarahmart/HARDMath#2]
Thanks for impressive work! I'm interested in few-shot learning. In the paper, 1-shot or 5-shot can largely improve the performance. Could you please share more information about few-shot learning. For example, do you use some searching method to find similar example questions, or the examples are randomly chosen. Thanks!

**Comment by jingxuanf0214** [comment]
Hi Beichen, 
Thanks for your interest in our work. The examples are randomly chosen problems spanning all categories from the big dataset HARDMath.csv. These are held out from the test dataset which we used to run the evaluations HARDMath_mini.csv. We put the example question and solution into a demo prompt (please look at demo_prompt.py for reference) and then incorporate the demo prompt into the main prompt (please look at create_prompt.py for reference). Hope this answers your question. Please let us know if anything is still unclear.

Jingxuan
